/**
 * 由 CoCo 源代码计划解包器解包
 *
 * 模块 ID：99
 */

module.exports = {
  wrapper: "BlockEditor_wrapper__3A0d7",
  blocklyWorkspace: "BlockEditor_blocklyWorkspace__3Xql1",
  readonly: "BlockEditor_readonly__kd2DI",
  upper: "BlockEditor_upper__EqYQt",
  nameDialog: "BlockEditor_nameDialog__33MsH",
  confirmBox: "BlockEditor_confirmBox__1a-NB",
  warningTips: "BlockEditor_warningTips__1qpTh",
  inputWrapper: "BlockEditor_inputWrapper__1MxfL",
  bottomTips: "BlockEditor_bottomTips__1Ld3Q",
  propertyBox: "BlockEditor_propertyBox__36y45",
  active: "BlockEditor_active__AoVkc",
  haveBottomTips: "BlockEditor_haveBottomTips__26bqJ",
  editDialog: "BlockEditor_editDialog__3MWzK",
  summary: "BlockEditor_summary__1mVTN",
  count: "BlockEditor_count__2BkK2",
  input: "BlockEditor_input__bKNK6",
  list: "BlockEditor_list__3ParX",
  save: "BlockEditor_save__3lr3q",
  emptyContent: "BlockEditor_emptyContent__iVi_N",
  image: "BlockEditor_image__1f1pr",
  label: "BlockEditor_label__1ZCJ3",
  editListDialog: "BlockEditor_editListDialog__3S_ZW",
  listItem: "BlockEditor_listItem__1fcTB",
  inputClose: "BlockEditor_inputClose__Y7bDq",
  listInput: "BlockEditor_listInput__2eG1h",
  inputLabel: "BlockEditor_inputLabel__2sare",
  dialogTitle: "BlockEditor_dialogTitle__3qnph",
  blockDropdown: "BlockEditor_blockDropdown__2IjzV",
  dynamicDataList: "BlockEditor_dynamicDataList__2909J",
  addOption: "BlockEditor_addOption__3egrX",
  optionTips: "BlockEditor_optionTips__3x7nN",
  btn: "BlockEditor_btn__Q-lDA",
  nullItem: "BlockEditor_nullItem__wVnvI",
  dropdownIconBox: "BlockEditor_dropdownIconBox__2MnDo",
  showCurrentScreenBg: "BlockEditor_showCurrentScreenBg__z-yg2",
  imageTextDataList: "BlockEditor_imageTextDataList__X5k5E",
  dropdownImageBox: "BlockEditor_dropdownImageBox__1HcK9",
  dropdownOption: "BlockEditor_dropdownOption__2US5s",
  imageEntryList: "BlockEditor_imageEntryList__2N7Cj",
  borderTop: "BlockEditor_borderTop__2rZa4",
  line: "BlockEditor_line__1beAa",
  lintErrorTips: "BlockEditor_lintErrorTips__2iYjU",
  errorAnimation: "BlockEditor_errorAnimation___7rLz",
  errorAnimationFrames: "BlockEditor_errorAnimationFrames__Tia_V",
  screenIconBox: "BlockEditor_screenIconBox__m_gi1",
  screenIconText: "BlockEditor_screenIconText__AtyEh"
}
